version: "3"
services:
  selenium:
    image: selenium/standalone-chrome
    container_name: 'selenium'
    ports:
      - "4444:4444"
  pyguitar:
    build: .
    ports:
      - "8888:8888"
    links:
      - selenium
    depends_on:
      - selenium
